[INSERT]
default = """
INSERT INTO metric.disk (
    collected_at, server_id, mount_point, total_bytes, used_bytes, free_bytes, percent
) VALUES (
    %(collected_at)s, %(server_id)s, %(mount_point)s, %(total_bytes)s, %(used_bytes)s, %(free_bytes)s, %(percent)s
)
ON CONFLICT (collected_at, server_id, mount_point) DO NOTHING
"""
