[INSERT]
default = """
INSERT INTO metadata.index_column (index_id, column_id, ordinal_position)
VALUES (%(index_id)s, %(column_id)s, %(ordinal_position)s)
"""

[DELETE]
by_index_id = """
DELETE FROM metadata.index_column WHERE index_id = ANY(%(ids)s)
"""
