[SELECT]
default = """
SELECT id, oid, schema_name, name, description
FROM "metadata"."table"
WHERE database_id = %(database_id)s
  AND deleted_at  IS NULL
"""

by_database_id_and_active = """
SELECT id, oid
FROM "metadata"."table"
WHERE database_id = %(database_id)s
AND deleted_at IS NULL
"""

[INSERT]
default = """
INSERT INTO "metadata"."table" (
    database_id,
    oid,
    schema_name,
    name,
    description
) VALUES (
    %(database_id)s,
    %(table_oid)s,
    %(schema_name)s,
    %(name)s,
    %(description)s
)
ON CONFLICT (database_id, oid) DO NOTHING;
"""

[UPDATE]
default = """
UPDATE "metadata"."table"
SET
    schema_name = %(schema_name)s,
    name = %(table_name)s,
    description = %(description)s,
    updated_at = now()
WHERE
    oid = %(table_oid)s
    AND database_id = %(database_id)s
    AND deleted_at IS NULL
    AND (
        schema_name IS DISTINCT FROM %(schema_name)s OR
        name IS DISTINCT FROM %(table_name)s OR
        description IS DISTINCT FROM %(description)s
    );
"""

soft_delete = """
UPDATE "metadata"."table"
SET
    deleted_at = now()
WHERE
    oid   = ANY(%(removed_oids)s::oid[])
    AND database_id = %(database_id)s
    AND deleted_at  IS NULL;
"""
